# Generated by Django 5.0 on 2023-12-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
