# Generated by Django 5.0 on 2024-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
